### ISSUE TITLE
Hi! question about Contribs!

### ISSUE THREAD

**Issue by loneicewolf** [MultSec/Modules#1]
I have a question about Contributions, is it open? I.e is contributions welcome? 
Thanks!
G

**Comment by Pengrey** [comment]
Yes, Contributions are most welcome. The only thing I ask is that you use mingw so that someone else can compile it in a linux env.

**Comment by loneicewolf** [comment]
ah sure! that is noted! 🫡 


<sub>Saluting from Sweden!</sub>
